-- ===========================================================================
-- Homepage trending events (Batch 26) — IDEMPOTENT / re-runnable.
--
-- Adds:
--   * public.homepage_trending_events — an admin-curated, slot-based list of
--     at most six events that surface on the homepage "Trending now" section.
--     There is deliberately NO existing featured/trending flag on parties:
--     curation lives in this table only, so an event's approval/ownership
--     semantics are untouched and the section can drop a curated event the
--     moment it is hidden, deleted or moves to the past (the join decides).
--     position is bounded to 1..6, and the loading page simply orders by it
--     (duplicates are impossible in practice because only the ≤6 chosen events
--     are ever renumbered by the curator UI; a UNIQUE(position) constraint is
--     deliberately NOT used so a batch renumber can never hit a transient
--     modifier conflict while swapping two adjacent slots).
--   * RLS: everyone may read the catalogue (whether the linked event is
--     visible to a caller is still decided by the parties RLS on the join, so
--     a drag into the past or an admin suspension instantly clears it from a
--     viewer's home). Inserts/updates/deletes require the existing
--     'events.edit' permission (seeded in Batch 24) — the same permission that
--     already gates admin event management, so no new permission is invented
--     and existing roles and role_permissions keep applying unchanged.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- 1. Trending catalogue table.
-- ---------------------------------------------------------------------------
create table if not exists public.homepage_trending_events (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.parties (id) on delete cascade,
  position smallint not null check (position between 1 and 6),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint homepage_trending_events_event_unique unique (event_id)
);

alter table public.homepage_trending_events enable row level security;

-- Anyone can read the catalogue; the joined parties RLS decides whether the
-- event itself is visible to the caller. A public read that never leaks the
-- events table (RLS on parties is enforced on the embedded join).
drop policy if exists "public read homepage trending" on public.homepage_trending_events;
create policy "public read homepage trending"
  on public.homepage_trending_events for select
  using (true);

-- Curators (holders of events.edit) manage the list. A single ALL policy with
-- both USING and WITH CHECK keeps every write path permission-gated.
drop policy if exists "staff manage homepage trending" on public.homepage_trending_events;
create policy "staff manage homepage trending"
  on public.homepage_trending_events for all
  using (public.user_has_permission((select auth.uid()), 'events.edit'))
  with check (public.user_has_permission((select auth.uid()), 'events.edit'));

create index if not exists homepage_trending_events_position_idx
  on public.homepage_trending_events (position);

-- Write access is intentionally limited to staff with events.edit; an
-- organizer (or the event owner) can never self-promote their own event.