-- ==========================================================================
-- Lagos Live live operations: host coupons, wallets, event profitability and
-- complimentary tickets. All money-moving or ticket-issuing actions are
-- server-side, permission checked and audit logged.
-- ========================================================================

-- Event-scoped coupons. Existing global promos remain valid with party_id NULL.
alter table public.promos add column if not exists party_id bigint references public.parties(id) on delete cascade;
alter table public.promos add column if not exists created_by uuid references auth.users(id) on delete set null;
create index if not exists promos_party_idx on public.promos(party_id, active);

-- Wallets are integer naira balances. The ledger is append-only; the balance is
-- updated only by the guarded RPC below.
create table if not exists public.wallets (
  user_id uuid primary key references auth.users(id) on delete cascade,
  balance integer not null default 0 check (balance >= 0),
  updated_at timestamptz not null default now()
);
create table if not exists public.wallet_ledger (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  amount integer not null check (amount <> 0),
  balance_after integer not null check (balance_after >= 0),
  kind text not null check (kind in ('admin_credit','admin_debit','offline_credit','deal_adjustment','gift_ticket_reserve','gift_ticket_release')),
  note text not null,
  reference text,
  actor_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists wallet_ledger_user_idx on public.wallet_ledger(user_id, created_at desc);
alter table public.wallets enable row level security;
alter table public.wallet_ledger enable row level security;
drop policy if exists "users read own wallet" on public.wallets;
create policy "users read own wallet" on public.wallets for select using (user_id = (select auth.uid()));
drop policy if exists "users read own wallet ledger" on public.wallet_ledger;
create policy "users read own wallet ledger" on public.wallet_ledger for select using (user_id = (select auth.uid()));

create or replace function public.adjust_wallet(
  p_user_id uuid,
  p_amount integer,
  p_kind text,
  p_note text,
  p_reference text default null
) returns public.wallets
language plpgsql security definer set search_path = public as $$
declare
  v_wallet public.wallets;
  v_kind text := p_kind;
begin
  if not public.user_has_permission((select auth.uid()), 'wallets.adjust') then
    raise exception 'Forbidden' using errcode = '42501';
  end if;
  if p_user_id is null or p_amount = 0 or coalesce(trim(p_note), '') = '' then
    raise exception 'A user, non-zero amount and note are required' using errcode = '22023';
  end if;
  if v_kind not in ('admin_credit','admin_debit','offline_credit','deal_adjustment') then
    raise exception 'Invalid wallet adjustment type' using errcode = '22023';
  end if;
  insert into public.wallets(user_id) values (p_user_id) on conflict do nothing;
  select * into v_wallet from public.wallets where user_id = p_user_id for update;
  if v_wallet.balance + p_amount < 0 then
    raise exception 'Wallet balance cannot become negative' using errcode = 'P0001';
  end if;
  update public.wallets set balance = balance + p_amount, updated_at = now()
    where user_id = p_user_id returning * into v_wallet;
  insert into public.wallet_ledger(user_id, amount, balance_after, kind, note, reference, actor_id)
    values (p_user_id, p_amount, v_wallet.balance, v_kind, trim(p_note), nullif(trim(p_reference), ''), (select auth.uid()));
  perform public.write_audit_log('wallet_adjusted', 'user', p_user_id::text,
    jsonb_build_object('amount', p_amount, 'kind', v_kind, 'note', p_note, 'reference', p_reference,
      'balance_after', v_wallet.balance));
  return v_wallet;
end;
$$;

create or replace function public.create_host_promo(
  p_party_id bigint, p_code text, p_discount_percent integer,
  p_description text default null, p_max_uses integer default null,
  p_starts_at timestamptz default null, p_ends_at timestamptz default null
) returns uuid
language plpgsql security definer set search_path = public as $$
declare v_id uuid; v_owner uuid;
begin
  select created_by into v_owner from public.parties where id = p_party_id;
  if v_owner is null or v_owner <> (select auth.uid()) then raise exception 'Only the event host can create this coupon' using errcode = '42501'; end if;
  if p_code is null or upper(trim(p_code)) !~ '^[A-Z0-9][A-Z0-9_-]{2,23}$' then raise exception 'Invalid coupon code'; end if;
  if p_discount_percent < 1 or p_discount_percent > 100 then raise exception 'Discount must be between 1 and 100 percent'; end if;
  if p_max_uses is not null and p_max_uses < 1 then raise exception 'Maximum uses must be at least 1'; end if;
  if p_starts_at is not null and p_ends_at is not null and p_starts_at > p_ends_at then raise exception 'Start time must be before end time'; end if;
  insert into public.promos(party_id, created_by, code, discount_percent, description, max_uses, starts_at, ends_at)
    values(p_party_id, (select auth.uid()), upper(trim(p_code)), p_discount_percent, nullif(trim(coalesce(p_description,'')),''), p_max_uses, p_starts_at, p_ends_at)
    returning id into v_id;
  perform public.write_audit_log('host_promo_created', 'event', p_party_id::text,
    jsonb_build_object('promo_id', v_id, 'code', upper(trim(p_code)), 'discount_percent', p_discount_percent));
  return v_id;
end;
$$;

-- Buyers can use a global admin promo or a coupon belonging to this event.
-- Replace the old validation query at the API layer to include party_id.

create or replace function public.event_profitability(p_party_id bigint)
returns table(event_id bigint, gross_revenue integer, discounts integer, refunds integer,
  platform_fee integer, net_platform_gain integer, host_earnings integer, paid_tickets bigint)
language sql security definer set search_path = public as $$
  select p.id,
    coalesce(sum(case when o.payment_status='confirmed' then o.total + coalesce(o.promo_discount,0) else 0 end),0)::integer,
    coalesce(sum(case when o.payment_status='confirmed' then coalesce(o.promo_discount,0) else 0 end),0)::integer,
    coalesce(sum(coalesce(o.refund_amount,0)),0)::integer,
    round(coalesce(sum(case when o.payment_status='confirmed' then o.total else 0 end),0) * 0.15)::integer,
    round(coalesce(sum(case when o.payment_status='confirmed' then o.total else 0 end),0) * 0.15)::integer,
    (coalesce(sum(case when o.payment_status='confirmed' then o.total else 0 end),0) - round(coalesce(sum(case when o.payment_status='confirmed' then o.total else 0 end),0) * 0.15))::integer,
    coalesce(sum(case when o.payment_status='confirmed' then o.quantity else 0 end),0)::bigint
  from public.parties p left join public.orders o on o.party_id=p.id
  where p.id=p_party_id
    and (public.user_has_permission((select auth.uid()), 'analytics.revenue')
      or public.user_has_permission((select auth.uid()), 'revenue.view'))
  group by p.id;
$$;
revoke all on function public.event_profitability(bigint) from public, anon;
grant execute on function public.event_profitability(bigint) to authenticated, service_role;

-- Complimentary tickets are real confirmed orders with total 0, so they have
-- QR codes and appear in attendee lists, but never enter paid revenue.
create or replace function public.issue_complimentary_ticket(
  p_party_id bigint, p_ticket_type_id bigint, p_quantity integer,
  p_email text, p_guest_name text default null, p_user_id uuid default null
) returns jsonb
language plpgsql security definer set search_path = public as $$
declare v_party public.parties; v_type public.ticket_types; v_ref text; v_order public.orders;
begin
  if not public.user_has_permission((select auth.uid()), 'tickets.complimentary') then raise exception 'Forbidden' using errcode='42501'; end if;
  if p_quantity is null or p_quantity < 1 or p_quantity > 20 or p_email is null or p_email !~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$' then raise exception 'Valid email and quantity 1–20 are required'; end if;
  select * into v_party from public.parties where id=p_party_id for update;
  if not found or v_party.status <> 'approved' or v_party.cancelled_at is not null then raise exception 'Event is not available'; end if;
  select * into v_type from public.ticket_types where id=p_ticket_type_id and party_id=p_party_id for update;
  if not found or not v_type.active or v_type.quantity-v_type.sold < p_quantity then raise exception 'Not enough tickets left on this tier'; end if;
  v_ref := 'COMP-' || upper(substr(replace(gen_random_uuid()::text,'-',''),1,12));
  insert into public.orders(user_id, customer_email, guest_name, ticket_access_token, ticket_access_expires_at, party_id, ticket_type_id, tier, quantity, unit_price, service_fee, total, order_ref, payment_ref, status, payment_status)
    values(p_user_id, lower(trim(p_email)), nullif(trim(p_guest_name),''), case when p_user_id is null then encode(gen_random_bytes(32),'hex') else null end,
      case when p_user_id is null then now() + interval '5 years' else null end, p_party_id, p_ticket_type_id, 'complimentary', p_quantity, 0, 0, 0, v_ref, v_ref, 'pending', 'pending') returning * into v_order;
  perform public.confirm_order_payment(v_order.id);
  select * into v_order from public.orders where id=v_order.id;
  perform public.write_audit_log('complimentary_ticket_issued', 'order', v_order.id::text,
    jsonb_build_object('party_id',p_party_id,'email',p_email,'quantity',p_quantity,'order_ref',v_order.order_ref));
  return jsonb_build_object('order_id',v_order.id,'order_ref',v_order.order_ref,'ticket_access_token',v_order.ticket_access_token,'email',v_order.customer_email);
end;
$$;
revoke all on function public.issue_complimentary_ticket(bigint,bigint,integer,text,text,uuid) from public, anon;
grant execute on function public.issue_complimentary_ticket(bigint,bigint,integer,text,text,uuid) to authenticated, service_role;

-- New staff capabilities are intentionally super-admin-only by default.
insert into public.permissions(name, resource, action, description, sensitive) values
 ('wallets.adjust','wallets','adjust','Credit or debit a user/host wallet',true),
 ('tickets.complimentary','tickets','complimentary','Issue complimentary tickets',true)
on conflict(name) do nothing;
insert into public.role_permissions(role_id, permission_id)
 select r.id,p.id from public.roles r cross join public.permissions p
 where r.name='super_admin' and p.name in ('wallets.adjust','tickets.complimentary')
on conflict do nothing;
